### ISSUE TITLE
批注模式下点击翻页

### ISSUE THREAD

**Issue by xrgzs** [RinLit-233-shiroko/PowerPoint-Touch-Assist#1]
PPT放映后，选择笔工具，进入批注模式，此时点击屏幕仍然可以翻页，不方便书写涉及到点的字符，希望增加相关检测机制

**Comment by RinLit-233-shiroko** [comment]
em虽然软件有滑动检测，但书写涉及到点的字符的确是个问题。
但很遗憾这个软件的运行方式并不允许我检测，很抱歉＞﹏＜

临时的解决方案是画点的时候多移动几个像素（这样就不会被翻页了）
